// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFUrwdYtXDjvd-2Dz-w4zvBG9oJOu96ZA',
    appId: '1:1021344279206:web:94fae9fc61469ae42a6267',
    messagingSenderId: '1021344279206',
    projectId: 'iot-attendance-appln',
    authDomain: 'iot-attendance-appln.firebaseapp.com',
    databaseURL: 'https://iot-attendance-appln-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-attendance-appln.appspot.com',
    measurementId: 'G-VN7HNBKFS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdU8BMm7tOO8w1SQuKsM_4ncnsovzs0RU',
    appId: '1:1021344279206:android:73c8d64589fd5daa2a6267',
    messagingSenderId: '1021344279206',
    projectId: 'iot-attendance-appln',
    databaseURL: 'https://iot-attendance-appln-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-attendance-appln.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBsIQ59f_76XHK4R4GVEFnF4lpGorOuAM',
    appId: '1:1021344279206:ios:7085e364c87b78782a6267',
    messagingSenderId: '1021344279206',
    projectId: 'iot-attendance-appln',
    databaseURL: 'https://iot-attendance-appln-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-attendance-appln.appspot.com',
    iosClientId: '1021344279206-vnibm5lhvllc10eea7pe7kk5lbgdibe4.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendance',
  );
}
